#!/usr/bin/env python3
"""Convert a paired image/binary-mask wound set into a YOLO segmentation dataset.

Sorbed's segmentation corpora (e.g. FUSeg via ``fetch_corpus.py``) store a wound
as a *binary mask* PNG whose stem matches its image. Ultralytics YOLO instead
wants, per image, a ``.txt`` label file of normalised polygon(s):

    <class> x1 y1 x2 y2 ... xn yn        # coords in [0, 1], class 0 = wound

This script walks ``<root>/<split>/images`` + ``<root>/<split>/labels`` (the
FUSeg layout, where "labels" holds mask PNGs), traces each mask's contours with
OpenCV, writes YOLO polygon ``.txt`` files, and lays the result out in the
directory shape Ultralytics expects plus a ``data.yaml``:

    <out>/images/{train,val}/*.png
    <out>/labels/{train,val}/*.txt
    <out>/data.yaml

Fine-tune (on a GPU, e.g. the AWS pod) with:

    yolo segment train model=yolo26n-seg.pt data=<out>/data.yaml imgsz=768 epochs=100

Nothing here needs a GPU; it is pure data preparation and safe to run on a laptop.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cv2
import numpy as np

# FUSeg splits map to YOLO's train/val; extend if a source uses other names.
_SPLIT_MAP = {"train": "train", "validation": "val", "val": "val"}
_MIN_CONTOUR_AREA_FRAC = 5e-4  # drop specks smaller than this fraction of the image
_POLY_EPS_FRAC = 0.002  # Douglas-Peucker simplification, fraction of the arc length


def mask_to_polygons(mask: np.ndarray) -> list[np.ndarray]:
    """Trace a binary mask into simplified, normalised polygons.

    Returns a list of ``(N, 2)`` float arrays in [0, 1] (x, y). Tiny specks and
    degenerate (<3 point) contours are dropped so YOLO never sees empty polygons.
    """
    h, w = mask.shape[:2]
    binary = (mask > 0).astype(np.uint8)
    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    polygons: list[np.ndarray] = []
    min_area = _MIN_CONTOUR_AREA_FRAC * h * w
    for contour in contours:
        if cv2.contourArea(contour) < min_area:
            continue
        eps = _POLY_EPS_FRAC * cv2.arcLength(contour, closed=True)
        approx = cv2.approxPolyDP(contour, eps, closed=True).reshape(-1, 2)
        if approx.shape[0] < 3:
            continue
        norm = approx.astype(np.float32) / np.array([w, h], dtype=np.float32)
        polygons.append(np.clip(norm, 0.0, 1.0))
    return polygons


def _write_label(path: Path, polygons: list[np.ndarray], cls: int = 0) -> None:
    lines = []
    for poly in polygons:
        coords = " ".join(f"{v:.6f}" for v in poly.reshape(-1))
        lines.append(f"{cls} {coords}")
    path.write_text("\n".join(lines) + ("\n" if lines else ""))


def convert_split(images_dir: Path, masks_dir: Path, out_root: Path, split: str) -> tuple[int, int]:
    """Convert one split; returns (images_written, images_with_no_wound)."""
    out_img = out_root / "images" / split
    out_lbl = out_root / "labels" / split
    out_img.mkdir(parents=True, exist_ok=True)
    out_lbl.mkdir(parents=True, exist_ok=True)

    written = empty = 0
    for img_path in sorted(images_dir.iterdir()):
        if img_path.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
            continue
        mask_path = masks_dir / img_path.name
        if not mask_path.is_file():
            continue
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            continue
        polygons = mask_to_polygons(mask)
        if not polygons:
            empty += 1
        # Symlink the image (no copy) and write its label next to it.
        link = out_img / img_path.name
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(img_path.resolve())
        _write_label(out_lbl / f"{img_path.stem}.txt", polygons)
        written += 1
    return written, empty


def write_data_yaml(out_root: Path) -> Path:
    yaml_path = out_root / "data.yaml"
    yaml_path.write_text(
        "# YOLO segmentation dataset — generated by training/prepare_yolo_seg.py\n"
        f"path: {out_root.resolve()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "names:\n"
        "  0: wound\n"
    )
    return yaml_path


def main() -> None:
    ap = argparse.ArgumentParser(description="Binary-mask wound set -> YOLO segmentation dataset.")
    ap.add_argument("--root", required=True, type=Path,
                    help="Source root with <split>/images and <split>/labels (mask PNGs).")
    ap.add_argument("--out", required=True, type=Path, help="Output YOLO dataset directory.")
    ap.add_argument("--splits", nargs="+", default=["train", "validation"],
                    help="Source split folder names to convert (default: train validation).")
    args = ap.parse_args()

    total_w = total_e = 0
    for src_split in args.splits:
        yolo_split = _SPLIT_MAP.get(src_split, src_split)
        images_dir = args.root / src_split / "images"
        masks_dir = args.root / src_split / "labels"
        if not images_dir.is_dir() or not masks_dir.is_dir():
            print(f"  skip {src_split}: missing images/ or labels/")
            continue
        w, e = convert_split(images_dir, masks_dir, args.out, yolo_split)
        total_w += w
        total_e += e
        print(f"  {src_split} -> {yolo_split}: {w} images ({e} with no wound polygon)")

    yaml_path = write_data_yaml(args.out)
    print(f"\nWrote {total_w} labels ({total_e} empty). data.yaml: {yaml_path}")
    print(f"Fine-tune: yolo segment train model=yolo26n-seg.pt data={yaml_path} imgsz=768 epochs=100")


if __name__ == "__main__":
    main()
