#!/usr/bin/env python3
"""Convert CO2Wounds-V2 into a YOLO segmentation dataset.

CO2Wounds-V2 (764 chronic-wound photos from leprosy patients, IEEE DataPort)
ships its own split with the masks kept in sibling ``*_anns`` directories and
stored as **0/1** PNGs whose *stem* — not full filename — matches the ``.jpg`` /
``.jpeg`` image::

    <root>/split/train/IMG1000.jpg        <root>/split/train_anns/IMG1000.png
    <root>/split/val/...                  <root>/split/val_anns/...
    <root>/split/test/...                 (no masks shipped — held back)

That differs from the FUSeg layout ``training/prepare_yolo_seg.py`` expects
(``<split>/images`` + ``<split>/labels``, matched by full filename), so this
script adapts the layout while reusing that module's contour tracing, label
writer and ``data.yaml`` emitter — one polygon convention across the project.

The **test** split is skipped: its masks are not distributed, so it cannot be
scored locally and must not be silently mixed into training.

    python -m training.prepare_co2wounds_seg \
        --root "data/corpus/co2wounds_v2/CO2Wounds-V2 Extended Chronic Wounds Dataset From Leprosy Patients" \
        --out data/yolo_co2wounds

Pure data preparation — no GPU, no network. Images are sym-linked, never copied.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import cv2

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from prepare_yolo_seg import _write_label, mask_to_polygons
else:  # pragma: no cover - exercised only when imported as a package
    from training.prepare_yolo_seg import _write_label, mask_to_polygons

_IMG_EXTS = {".jpg", ".jpeg", ".png"}
# CO2Wounds split dir -> YOLO split dir. "test" is absent on purpose (no masks).
_SPLITS = {"train": "train", "val": "val"}


def convert_split(
    images_dir: Path, masks_dir: Path, out_root: Path, split: str
) -> tuple[int, int, int]:
    """Convert one CO2Wounds split, matching masks by stem.

    Returns ``(written, empty, missing_mask)``: images linked with a label,
    images whose mask traced to no polygon, and images with no mask file at all.
    """
    out_img = out_root / "images" / split
    out_lbl = out_root / "labels" / split
    out_img.mkdir(parents=True, exist_ok=True)
    out_lbl.mkdir(parents=True, exist_ok=True)

    # Stem -> mask path, so a .jpg image finds its .png mask.
    by_stem = {p.stem: p for p in masks_dir.iterdir() if p.suffix.lower() in _IMG_EXTS}

    written = empty = missing = 0
    for img_path in sorted(images_dir.iterdir()):
        if img_path.suffix.lower() not in _IMG_EXTS:
            continue
        mask_path = by_stem.get(img_path.stem)
        if mask_path is None:
            missing += 1
            continue
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            missing += 1
            continue
        polygons = mask_to_polygons(mask)  # treats any non-zero as foreground
        if not polygons:
            empty += 1
        link = out_img / img_path.name
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(img_path.resolve())
        _write_label(out_lbl / f"{img_path.stem}.txt", polygons)
        written += 1
    return written, empty, missing


def write_data_yaml(out_root: Path) -> Path:
    """Emit the Ultralytics dataset descriptor for this set."""
    yaml_path = out_root / "data.yaml"
    yaml_path.write_text(
        "# YOLO segmentation dataset — generated by training/prepare_co2wounds_seg.py\n"
        f"path: {out_root.resolve()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "names:\n"
        "  0: wound\n"
    )
    return yaml_path


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="CO2Wounds-V2 -> YOLO segmentation dataset.")
    ap.add_argument("--root", required=True, type=Path,
                    help="Extracted CO2Wounds-V2 directory (the one holding split/, imgs/, masks/).")
    ap.add_argument("--out", required=True, type=Path, help="Output YOLO dataset directory.")
    return ap.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    split_root = args.root / "split"
    if not split_root.is_dir():
        raise SystemExit(f"no split/ directory under {args.root}")

    total = 0
    for src, dst in _SPLITS.items():
        images_dir = split_root / src
        masks_dir = split_root / f"{src}_anns"
        if not images_dir.is_dir() or not masks_dir.is_dir():
            print(f"  {src}: missing {images_dir.name} or {masks_dir.name} — skipped")
            continue
        written, empty, missing = convert_split(images_dir, masks_dir, args.out, dst)
        total += written
        note = f"{written} images -> {dst}"
        if empty:
            note += f", {empty} with no traceable wound"
        if missing:
            note += f", {missing} skipped (no mask)"
        print(f"  {src}: {note}")

    yaml_path = write_data_yaml(args.out)
    print(f"{total} images total; wrote {yaml_path}")
    print("note: the official 'test' split ships no masks and is deliberately excluded.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
