#!/usr/bin/env python3
"""Turn DFUTissue into a YOLO wound-segmentation dataset to strengthen the segmenter.

The wound segmenter (trained on FUSeg foot ulcers) localises poorly on tissue-style
images: on DFUTissue it misses ~12% entirely and averages Dice ~0.47 even at a low
confidence. Its DFUTissue annotations mark tissue classes (1..3) inside the wound, so
``mask > 0`` is a usable binary wound mask. This converts DFUTissue's TrainVal split
into YOLO polygon labels (reusing ``prepare_yolo_seg.mask_to_polygons``) and lays it
out for fine-tuning the segmenter — **holding the Test split out** so mask-quality
Dice on DFUTissue Test stays an honest, leakage-free measurement.

    python -m training.prepare_dfutissue_seg --out data/dfutissue_yolo
    # then fine-tune the existing weights on it (GPU/Colab recommended):
    yolo segment train model=runs/segment/runs_wound/yolo26n_fuseg/weights/best.pt \
        data=data/dfutissue_yolo/data.yaml imgsz=768 epochs=80
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

import cv2

from training.prepare_yolo_seg import _write_label, mask_to_polygons

_ROOT = Path("data/corpus/dfutissue/DFUTissue/Labeled/Original")
_EXTS = {".png", ".jpg", ".jpeg"}


def _convert(items, img_dir: Path, ann_dir: Path, out_root: Path, split: str) -> tuple[int, int]:
    out_img = out_root / "images" / split
    out_lbl = out_root / "labels" / split
    out_img.mkdir(parents=True, exist_ok=True)
    out_lbl.mkdir(parents=True, exist_ok=True)
    written = empty = 0
    for name in items:
        ann = cv2.imread(str(ann_dir / name), cv2.IMREAD_GRAYSCALE)
        if ann is None:
            continue
        polys = mask_to_polygons(ann)          # ann > 0 == wound
        if not polys:
            empty += 1
        link = out_img / name
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to((img_dir / name).resolve())
        _write_label(out_lbl / f"{Path(name).stem}.txt", polys)
        written += 1
    return written, empty


def main() -> None:
    ap = argparse.ArgumentParser(description="DFUTissue -> YOLO wound-seg dataset (Test held out).")
    ap.add_argument("--dfutissue-root", type=Path, default=_ROOT)
    ap.add_argument("--out", required=True, type=Path, help="Output YOLO dataset dir.")
    ap.add_argument("--val-frac", type=float, default=0.15, help="Fraction of TrainVal used as val.")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    img_dir = args.dfutissue_root / "Images" / "TrainVal"
    ann_dir = args.dfutissue_root / "Annotations" / "TrainVal"
    if not img_dir.is_dir() or not ann_dir.is_dir():
        raise FileNotFoundError(f"expected {img_dir} and {ann_dir}")

    names = sorted(p.name for p in img_dir.iterdir()
                   if p.suffix.lower() in _EXTS and (ann_dir / p.name).is_file())
    random.Random(args.seed).shuffle(names)
    n_val = max(1, int(len(names) * args.val_frac))
    val, train = names[:n_val], names[n_val:]

    tw, te = _convert(train, img_dir, ann_dir, args.out, "train")
    vw, ve = _convert(val, img_dir, ann_dir, args.out, "val")

    (args.out / "data.yaml").write_text(
        "# DFUTissue wound-seg (generated by training/prepare_dfutissue_seg.py)\n"
        f"path: {args.out.resolve()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "names:\n  0: wound\n"
    )
    print(f"train: {tw} imgs ({te} without a wound polygon)")
    print(f"val:   {vw} imgs ({ve} without a wound polygon)")
    print(f"data.yaml -> {args.out / 'data.yaml'}  (DFUTissue Test held out for honest Dice)")
    print("Fine-tune: yolo segment train "
          f"model=runs/segment/runs_wound/yolo26n_fuseg/weights/best.pt data={args.out/'data.yaml'} "
          "imgsz=768 epochs=80")


if __name__ == "__main__":
    main()
